package popups;

import POJO.SupplierData;
import customComponents.*;
import database.Controller;
import static database.Controller.getAllSupplier;
import static database.Controller.getSupplierModel;
import java.awt.Color;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import static database.Controller.*;

/**
 *
 * @author Xenon
 */
public class DetailTransaksi extends javax.swing.JDialog {

    /**
     * Creates new form TambahPelanggan
     */


    public DetailTransaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DetailTransaksi() {
        initComponents();
    }
    
    public DetailTransaksi(int idBarang, int idCustomer, int idPekerja, String metodeBayar, String hargaJual, String tanggalJual) {
        initComponents();
        textMetodeBayar.setText(metodeBayar);
        textTotal.setText(hargaJual);
        textDate.setText(tanggalJual);
        textCustomerId.setText(String.valueOf(idCustomer));
        
        Vector barang = getProdukbyId(idBarang);

        labelNama.setText((String) barang.get(0));
        labelDeskripsi.setText((String) barang.get(1));
        labelWeight.setText((String) barang.get(2));
        labelKarat.setText((String) barang.get(3));
        labelType.setText((String) barang.get(4));
        labelKategori.setText((String) barang.get(5));
        labelSupplier.setText((String) barang.get(6));
        
        Vector pelanggan = getCustomerByID(idCustomer);
        
        textNamaCustomer.setText((String) pelanggan.get(0));
        textPhone.setText((String) pelanggan.get(1));
        textAlamat.setText((String) pelanggan.get(2));
        
        textStaf.setText(getStafNameByID(idPekerja));

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TambahPelangganPanel = new javax.swing.JPanel();
        TitleText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        textMetodeBayar = new javax.swing.JLabel();
        jlabel7 = new javax.swing.JLabel();
        textTotal = new javax.swing.JLabel();
        textDate = new javax.swing.JLabel();
        textStaf = new javax.swing.JLabel();
        textCustomerId = new javax.swing.JLabel();
        textNamaCustomer = new javax.swing.JLabel();
        textPhone = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAlamat = new javax.swing.JTextArea();
        panelInfoProduk = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelDeskripsi = new javax.swing.JLabel();
        labelWeight = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelKarat = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelKategori = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelSupplier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Pelanggan");
        setSize(new java.awt.Dimension(400, 550));

        TambahPelangganPanel.setBackground(new java.awt.Color(255, 231, 192));
        TambahPelangganPanel.setPreferredSize(new java.awt.Dimension(400, 550));

        TitleText.setBackground(new java.awt.Color(102, 0, 0));
        TitleText.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        TitleText.setForeground(new java.awt.Color(102, 0, 0));
        TitleText.setText("Nota Penjualan");

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Tanggal :");

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Nama Staf :");

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("ID Pelanggan :");

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Nama :");

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Alamat :");

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("No Telp :");

        jlabel6.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(102, 0, 0));
        jlabel6.setText("Total : ");

        textMetodeBayar.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        textMetodeBayar.setForeground(new java.awt.Color(102, 0, 0));
        textMetodeBayar.setText("<HargaTotal>");

        jlabel7.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel7.setForeground(new java.awt.Color(102, 0, 0));
        jlabel7.setText("Metode Bayar :");

        textTotal.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        textTotal.setForeground(new java.awt.Color(102, 0, 0));
        textTotal.setText("<HargaTotal>");

        textDate.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        textDate.setForeground(new java.awt.Color(102, 0, 0));
        textDate.setText("<HargaTotal>");

        textStaf.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        textStaf.setForeground(new java.awt.Color(102, 0, 0));
        textStaf.setText("<HargaTotal>");

        textCustomerId.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        textCustomerId.setForeground(new java.awt.Color(102, 0, 0));
        textCustomerId.setText("<HargaTotal>");

        textNamaCustomer.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        textNamaCustomer.setForeground(new java.awt.Color(102, 0, 0));
        textNamaCustomer.setText("<HargaTotal>");

        textPhone.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        textPhone.setForeground(new java.awt.Color(102, 0, 0));
        textPhone.setText("<HargaTotal>");

        textAlamat.setColumns(21);
        textAlamat.setRows(4);
        textAlamat.setEditable(false);
        jScrollPane2.setViewportView(textAlamat);

        panelInfoProduk.setBackground(java.awt.Color.white);
        panelInfoProduk.setBorder(new BubbleBorderJPanel(Color.WHITE, 10, 20, 0));
        panelInfoProduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.gray);
        jLabel2.setText("Deskripsi:");
        panelInfoProduk.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        labelDeskripsi.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        labelDeskripsi.setForeground(java.awt.Color.black);
        labelDeskripsi.setText("Deskripsi");
        panelInfoProduk.add(labelDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        labelWeight.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        labelWeight.setForeground(java.awt.Color.black);
        labelWeight.setText("Weight");
        panelInfoProduk.add(labelWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        labelNama.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        labelNama.setForeground(java.awt.Color.black);
        labelNama.setText("Nama");
        panelInfoProduk.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel10.setForeground(java.awt.Color.gray);
        jLabel10.setText("Berat:");
        panelInfoProduk.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel11.setForeground(java.awt.Color.gray);
        jLabel11.setText("Karat:");
        panelInfoProduk.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        labelKarat.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        labelKarat.setForeground(java.awt.Color.black);
        labelKarat.setText("Karat");
        panelInfoProduk.add(labelKarat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel13.setForeground(java.awt.Color.gray);
        jLabel13.setText("Tipe:");
        panelInfoProduk.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        labelType.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        labelType.setForeground(java.awt.Color.black);
        labelType.setText("Type");
        panelInfoProduk.add(labelType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel15.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel15.setForeground(java.awt.Color.gray);
        jLabel15.setText("Kategori:");
        panelInfoProduk.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        labelKategori.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        labelKategori.setForeground(java.awt.Color.black);
        labelKategori.setText("Kategori");
        panelInfoProduk.add(labelKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel17.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel17.setForeground(java.awt.Color.gray);
        jLabel17.setText("Supplier:");
        panelInfoProduk.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        labelSupplier.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        labelSupplier.setForeground(java.awt.Color.black);
        labelSupplier.setText("Supplier");
        panelInfoProduk.add(labelSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        javax.swing.GroupLayout TambahPelangganPanelLayout = new javax.swing.GroupLayout(TambahPelangganPanel);
        TambahPelangganPanel.setLayout(TambahPelangganPanelLayout);
        TambahPelangganPanelLayout.setHorizontalGroup(
            TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahPelangganPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TambahPelangganPanelLayout.createSequentialGroup()
                        .addComponent(TitleText)
                        .addContainerGap())
                    .addGroup(TambahPelangganPanelLayout.createSequentialGroup()
                        .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TambahPelangganPanelLayout.createSequentialGroup()
                                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(12, 12, 12)
                                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textDate)
                                    .addComponent(textStaf)))
                            .addComponent(panelInfoProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TambahPelangganPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCustomerId)
                                    .addComponent(textNamaCustomer)
                                    .addComponent(textPhone)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(8, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TambahPelangganPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlabel6)
                                    .addComponent(jlabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textMetodeBayar)
                                    .addComponent(textTotal))
                                .addGap(42, 42, 42))))))
        );
        TambahPelangganPanelLayout.setVerticalGroup(
            TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahPelangganPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TitleText)
                .addGap(20, 20, 20)
                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TambahPelangganPanelLayout.createSequentialGroup()
                        .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textDate))
                        .addGap(18, 18, 18)
                        .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textStaf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelInfoProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TambahPelangganPanelLayout.createSequentialGroup()
                        .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textCustomerId))
                        .addGap(18, 18, 18)
                        .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textNamaCustomer))
                        .addGap(18, 18, 18)
                        .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textPhone))
                        .addGap(18, 18, 18)
                        .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel6)
                            .addComponent(textTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMetodeBayar))))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TambahPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TambahPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        JFrame a = new JFrame();
        DetailTransaksi dialog = new DetailTransaksi(a, true);
        //a.setPreferredSize(dialog.getPreferredSize());
        dialog.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TambahPelangganPanel;
    private javax.swing.JLabel TitleText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel labelDeskripsi;
    private javax.swing.JLabel labelKarat;
    private javax.swing.JLabel labelKategori;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelSupplier;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel labelWeight;
    private javax.swing.JPanel panelInfoProduk;
    private javax.swing.JTextArea textAlamat;
    private javax.swing.JLabel textCustomerId;
    private javax.swing.JLabel textDate;
    private javax.swing.JLabel textMetodeBayar;
    private javax.swing.JLabel textNamaCustomer;
    private javax.swing.JLabel textPhone;
    private javax.swing.JLabel textStaf;
    private javax.swing.JLabel textTotal;
    // End of variables declaration//GEN-END:variables
}
