package popups;

import POJO.SupplierData;
import customComponents.*;
import database.Controller;
import static database.Controller.getAllSupplier;
import static database.Controller.getSupplierModel;
import java.awt.Color;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Xenon
 */
public class Supplier extends javax.swing.JDialog {

    /**
     * Creates new form TambahPelanggan
     */
    Vector<SupplierData> dataSupplier;
    DocumentListener docListener;

    public Supplier(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Supplier() {
        initComponents();
        System.out.println("MASUK SINI");
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        dataSupplier = getAllSupplier();

        ListSelectionModel lsm = listSupplier.getSelectionModel();
        lsm.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (lse.getValueIsAdjusting()) {
                    btnUbah.setEnabled(true);
                    btnHapus.setEnabled(true);
                    SupplierData temp = dataSupplier.get(listSupplier.getSelectedIndex());
                    fieldNama.setText(temp.getNama());
                    fieldNama.setForeground(Color.BLACK);
                    fieldNoTelp.setText(temp.getNotelp());
                    fieldNoTelp.setForeground(Color.BLACK);
                    textAreaAlamat.setText(temp.getAlamat());
                    textAreaAlamat.setForeground(Color.BLACK);
                }
            }
        });

        docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                showClearBtn();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {

            }

            @Override
            public void changedUpdate(DocumentEvent de) {

            }

            private void showClearBtn() {
                btnClear.setVisible(true);
            }
        };

        fieldNama.getDocument().addDocumentListener(docListener);
        fieldNoTelp.getDocument().addDocumentListener(docListener);
        textAreaAlamat.getDocument().addDocumentListener(docListener);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TambahPelangganPanel = new javax.swing.JPanel();
        TitleText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        fieldNama = new CorneredJTextField();
        fieldNoTelp = new javax.swing.JTextField();
        fieldNoTelp = new CorneredJTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaAlamat = new javax.swing.JTextArea();
        textAreaAlamat = new CorneredJTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSupplier = new javax.swing.JList<>();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnClear.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Pelanggan");
        setSize(new java.awt.Dimension(400, 550));

        TambahPelangganPanel.setBackground(new java.awt.Color(255, 231, 192));
        TambahPelangganPanel.setPreferredSize(new java.awt.Dimension(400, 550));

        TitleText.setBackground(new java.awt.Color(102, 0, 0));
        TitleText.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        TitleText.setForeground(new java.awt.Color(102, 0, 0));
        TitleText.setText("Supplier");

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Nama Supplier");

        fieldNama.setForeground(java.awt.Color.gray);
        fieldNama.setText("Masukkan nama supplier.");
        fieldNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNamaFocusLost(evt);
            }
        });

        fieldNoTelp.setForeground(java.awt.Color.gray);
        fieldNoTelp.setText("Masukkan no telp.");
        fieldNoTelp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNoTelpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNoTelpFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("No Telepon");

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Alamat");

        textAreaAlamat.setColumns(20);
        textAreaAlamat.setForeground(java.awt.Color.gray);
        textAreaAlamat.setRows(5);
        textAreaAlamat.setText("Masukkan alamat.");
        textAreaAlamat.setBorder(null);
        textAreaAlamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textAreaAlamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textAreaAlamatFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(textAreaAlamat);
        jScrollPane1.setBorder(null);

        listSupplier.setModel(getSupplierModel());
        listSupplier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                listSupplierFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(listSupplier);

        btnHapus.setBackground(new java.awt.Color(89, 38, 1));
        btnHapus.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnHapus.setForeground(java.awt.Color.white);
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(89, 38, 1));
        btnTambah.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnTambah.setForeground(java.awt.Color.white);
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(89, 38, 1));
        btnUbah.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnUbah.setForeground(java.awt.Color.white);
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("List Supplier");

        btnClear.setBackground(new java.awt.Color(89, 38, 1));
        btnClear.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnClear.setForeground(java.awt.Color.white);
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TambahPelangganPanelLayout = new javax.swing.GroupLayout(TambahPelangganPanel);
        TambahPelangganPanel.setLayout(TambahPelangganPanelLayout);
        TambahPelangganPanelLayout.setHorizontalGroup(
            TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahPelangganPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TambahPelangganPanelLayout.createSequentialGroup()
                            .addComponent(btnHapus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                            .addComponent(btnUbah)
                            .addGap(54, 54, 54)
                            .addComponent(btnTambah))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldNoTelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TambahPelangganPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear))
                        .addComponent(TitleText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldNama, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        TambahPelangganPanelLayout.setVerticalGroup(
            TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahPelangganPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TitleText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(TambahPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TambahPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TambahPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNamaFocusGained
        if (fieldNama.getText().equals("Masukkan nama supplier.")) {
            fieldNama.setText("");
            fieldNama.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fieldNamaFocusGained

    private void fieldNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNamaFocusLost
        if (fieldNama.getText().equals("")) {
            fieldNama.setText("Masukkan nama supplier.");
            fieldNama.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_fieldNamaFocusLost

    private void fieldNoTelpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNoTelpFocusGained
        if (fieldNoTelp.getText().equals("Masukkan no telp.")) {
            fieldNoTelp.setText("");
            fieldNoTelp.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fieldNoTelpFocusGained

    private void fieldNoTelpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNoTelpFocusLost
        if (fieldNoTelp.getText().equals("")) {
            fieldNoTelp.setText("Masukkan no telp.");
            fieldNoTelp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_fieldNoTelpFocusLost

    private void textAreaAlamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textAreaAlamatFocusGained
        if (textAreaAlamat.getText().equals("Masukkan alamat.")) {
            textAreaAlamat.setText("");
            textAreaAlamat.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textAreaAlamatFocusGained

    private void textAreaAlamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textAreaAlamatFocusLost
        if (textAreaAlamat.getText().equals("")) {
            textAreaAlamat.setText("Masukkan alamat.");
            textAreaAlamat.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_textAreaAlamatFocusLost

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        boolean isExist = false;
        for (int i = 0; i < listSupplier.getModel().getSize(); i++) {
            if (listSupplier.getModel().getElementAt(i).equalsIgnoreCase(fieldNama.getText())) {
                isExist = true;
            }
        }
        if (isExist) {
            int reply = JOptionPane.showConfirmDialog(null, "nama supplier sudah ada, apakah ingin melanjutkan?",
                    "Perhatian", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                SupplierData newSupplier = new SupplierData();
                newSupplier.setNama(fieldNama.getText());
                newSupplier.setAlamat(textAreaAlamat.getText());
                newSupplier.setNotelp(fieldNoTelp.getText());
                Controller.addSupplier(newSupplier);
            }
        } else {
            SupplierData newSupplier = new SupplierData();
            newSupplier.setNama(fieldNama.getText());
            newSupplier.setAlamat(textAreaAlamat.getText());
            newSupplier.setNotelp(fieldNoTelp.getText());
            Controller.addSupplier(newSupplier);
        }

        textAreaAlamat.setText("Masukkan alamat.");
        textAreaAlamat.setForeground(Color.GRAY);
        fieldNoTelp.setText("Masukkan no telp.");
        fieldNoTelp.setForeground(Color.GRAY);
        fieldNama.setText("Masukkan nama supplier.");
        fieldNama.setForeground(Color.GRAY);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        listSupplier.setModel(getSupplierModel());
        dataSupplier = getAllSupplier();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        boolean isExist = false;
        for (int i = 0; i < listSupplier.getModel().getSize(); i++) {
            if (listSupplier.getModel().getElementAt(i).equalsIgnoreCase(fieldNama.getText())) {
                isExist = true;
            }
        }
        if (isExist) {
            int reply = JOptionPane.showConfirmDialog(null, "Nama supplier sudah ada, apakah ingin melanjutkan?",
                    "Perhatian", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                Controller.updateSupplier(dataSupplier.get(listSupplier.getSelectedIndex()).getId(),
                        fieldNama.getText(),
                        textAreaAlamat.getText(),
                        fieldNoTelp.getText());
            }
        } else {
            Controller.updateSupplier(dataSupplier.get(listSupplier.getSelectedIndex()).getId(),
                    fieldNama.getText(),
                    textAreaAlamat.getText(),
                    fieldNoTelp.getText());
        }

        textAreaAlamat.setText("Masukkan alamat.");
        textAreaAlamat.setForeground(Color.GRAY);
        fieldNoTelp.setText("Masukkan no telp.");
        fieldNoTelp.setForeground(Color.GRAY);
        fieldNama.setText("Masukkan nama supplier.");
        fieldNama.setForeground(Color.GRAY);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        listSupplier.setModel(getSupplierModel());
        dataSupplier = getAllSupplier();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int id =  dataSupplier.get(listSupplier.getSelectedIndex()).getId();
        int reply = JOptionPane.showConfirmDialog(null, "Menghapus supplier " + fieldNama.getText(), "Hapus Supplier", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            Controller.deleteSupplier(id);
            listSupplier.clearSelection();
        }
        listSupplier.setModel(getSupplierModel());
        textAreaAlamat.setText("Masukkan alamat.");
        textAreaAlamat.setForeground(Color.GRAY);
        fieldNoTelp.setText("Masukkan no telp.");
        fieldNoTelp.setForeground(Color.GRAY);
        fieldNama.setText("Masukkan nama supplier.");
        fieldNama.setForeground(Color.GRAY);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);

    }//GEN-LAST:event_btnHapusActionPerformed

    private void listSupplierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listSupplierFocusLost
        
    }//GEN-LAST:event_listSupplierFocusLost

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        textAreaAlamat.setText("Masukkan alamat.");
        textAreaAlamat.setForeground(Color.GRAY);
        fieldNoTelp.setText("Masukkan no telp.");
        fieldNoTelp.setForeground(Color.GRAY);
        fieldNama.setText("Masukkan nama supplier.");
        fieldNama.setForeground(Color.GRAY);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnClear.setVisible(false);
    }//GEN-LAST:event_btnClearActionPerformed

    public static void main(String args[]) {
        JFrame a = new JFrame();
        Supplier dialog = new Supplier(a, true);
        //a.setPreferredSize(dialog.getPreferredSize());
        dialog.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TambahPelangganPanel;
    private javax.swing.JLabel TitleText;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNoTelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listSupplier;
    private javax.swing.JTextArea textAreaAlamat;
    // End of variables declaration//GEN-END:variables
}
