package panels;

/**
 *
 * @author Xenon
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard1
     */
    public DashboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transaksiField = new javax.swing.JTextField();
        profitField = new javax.swing.JTextField();
        employeeField = new javax.swing.JTextField();
        jamField = new javax.swing.JTextField();
        tanggalField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 231, 192));

        transaksiField.setBackground(new java.awt.Color(102, 0, 0));
        transaksiField.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        transaksiField.setForeground(new java.awt.Color(255, 255, 255));
        transaksiField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        transaksiField.setText("Total Transaksi");

        profitField.setBackground(new java.awt.Color(102, 0, 0));
        profitField.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        profitField.setForeground(new java.awt.Color(255, 255, 255));
        profitField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        profitField.setText("Profit Hari Ini");

        employeeField.setBackground(new java.awt.Color(102, 0, 0));
        employeeField.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        employeeField.setForeground(new java.awt.Color(255, 255, 255));
        employeeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        employeeField.setText("Employee Of The Day");

        jamField.setBackground(new java.awt.Color(255, 231, 192));
        jamField.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jamField.setForeground(new java.awt.Color(102, 0, 0));
        jamField.setText("21:36");
        jamField.setBorder(null);

        tanggalField.setBackground(new java.awt.Color(255, 231, 192));
        tanggalField.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        tanggalField.setForeground(new java.awt.Color(102, 0, 0));
        tanggalField.setText("21-10-2018");
        tanggalField.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profitField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transaksiField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(404, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(transaksiField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(profitField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(employeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField employeeField;
    private javax.swing.JTextField jamField;
    private javax.swing.JTextField profitField;
    private javax.swing.JTextField tanggalField;
    private javax.swing.JTextField transaksiField;
    // End of variables declaration//GEN-END:variables
}
