package panels;

import database.Controller;
import static database.Controller.getDateAndTime;
import static database.Controller.getEmployeeOftheDay;
import static database.Controller.getProfitHariIni;
import static database.Controller.getTransaksiCount;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Xenon
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard1
     */
    public DashboardPanel() {
        initComponents();
        syncDate();

        showJumlahTransaksi();
        showProfitHariIni();
        showEmployeeOftheDay();
    }

    private void syncDate() {
        String[] dateAndTime = getDateAndTime();
        timeText.setText(dateAndTime[0]);
        dateText.setText(dateAndTime[1]);
        System.out.println(dateAndTime[1]);
        Timer date = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String[] dateAndTime = getDateAndTime();
                timeText.setText(dateAndTime[0]);
                dateText.setText(dateAndTime[1]);

                showJumlahTransaksi();
                showProfitHariIni();
                showEmployeeOftheDay();
            }
        });
        date.start();
    }

    private void showJumlahTransaksi() {
        transaksiField.setText(getTransaksiCount());
    }

    private void showProfitHariIni() {
        profitField.setText(getProfitHariIni());
    }

    private void showEmployeeOftheDay() {
        Vector pekerja = getEmployeeOftheDay();
        //ystem.out.println(pekerja.get(0));
        if (!pekerja.isEmpty()) {
            employeeField.setText((String) pekerja.get(0));
        } else {
            employeeField.setText("Belum ada transaksi hari ini");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transaksiField = new javax.swing.JTextField();
        profitField = new javax.swing.JTextField();
        employeeField = new javax.swing.JTextField();
        timeText = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 231, 192));

        transaksiField.setBackground(new java.awt.Color(102, 0, 0));
        transaksiField.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        transaksiField.setForeground(new java.awt.Color(255, 255, 255));
        transaksiField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        transaksiField.setText("Total Transaksi");
        transaksiField.setEditable(false);

        profitField.setBackground(new java.awt.Color(102, 0, 0));
        profitField.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        profitField.setForeground(new java.awt.Color(255, 255, 255));
        profitField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        profitField.setText("Profit Hari Ini");

        employeeField.setBackground(new java.awt.Color(102, 0, 0));
        employeeField.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        employeeField.setForeground(new java.awt.Color(255, 255, 255));
        employeeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        employeeField.setText("Employee Of The Day");

        timeText.setBackground(new java.awt.Color(102, 0, 0));
        timeText.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        timeText.setForeground(new java.awt.Color(102, 0, 0));
        timeText.setText("<TIME>");

        dateText.setBackground(new java.awt.Color(102, 0, 0));
        dateText.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        dateText.setForeground(new java.awt.Color(102, 0, 0));
        dateText.setText("<DD-MM-YYYY>");

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Total Profit Kotor hari ini :");

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Employee Of the Day :");

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Total transaksi hari ini :");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateText)
                        .addGap(9, 9, 9))
                    .addComponent(timeText))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transaksiField, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profitField, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(timeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaksiField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profitField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
    }// </editor-fold>//GEN-END:initComponents
        public static void main(String args[]) {
        Controller con = new Controller();
        JFrame a = new JFrame();
        a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        DashboardPanel panel = new DashboardPanel();
        //a.setPreferredSize(dialog.getPreferredSize());
        a.setSize(panel.getPreferredSize());
        a.setContentPane(panel);
        a.setVisible(true);
        System.out.println("Width : " + a.getWidth());
        System.out.println("Height : " + a.getHeight());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateText;
    private javax.swing.JTextField employeeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField profitField;
    private javax.swing.JLabel timeText;
    private javax.swing.JTextField transaksiField;
    // End of variables declaration//GEN-END:variables
}
