package panels;

/**
 *
 * @author Xenon
 */
import CustomJTables.CustomTableCellRenderer;
import customComponents.*;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JFrame;
import popups.*;

public class Transaksi extends javax.swing.JPanel {

    /**
     * Creates new form Staff
     */
    public Transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        TitleText = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        fieldCariProduk = new javax.swing.JTextField();
        fieldCariProduk = new CorneredJTextField();
        jlabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dateText = new javax.swing.JLabel();
        timeText = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        labelNamaStaff = new javax.swing.JLabel();
        LabelNamaPelanggan = new javax.swing.JLabel();
        buttonPilihStaf = new javax.swing.JButton();
        buttonPilihPelanggan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduk = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTroli = new javax.swing.JTable();
        TitleText1 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        TitleText2 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        fieldCariTroli = new javax.swing.JTextField();
        fieldCariTroli = new CorneredJTextField();
        jlabel5 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        jlabel7 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        panelInfoProduk = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jlabel8 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 231, 192));
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(980, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleText.setBackground(new java.awt.Color(102, 0, 0));
        TitleText.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        TitleText.setForeground(new java.awt.Color(102, 0, 0));
        TitleText.setText("Transaksi");
        add(TitleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 42, -1, -1));

        buttonTambah.setBackground(new java.awt.Color(89, 38, 1));
        buttonTambah.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        buttonTambah.setForeground(java.awt.Color.white);
        buttonTambah.setText("Tambah Transaksi");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });
        add(buttonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, -1, 37));

        fieldCariProduk.setForeground(java.awt.Color.gray);
        fieldCariProduk.setText("Ketik pencarian");
        fieldCariProduk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCariProdukFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCariProdukFocusLost(evt);
            }
        });
        add(fieldCariProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 103, 191, -1));

        jlabel.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel.setForeground(new java.awt.Color(102, 0, 0));
        jlabel.setText("Tanggal Transaksi");
        add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 97, -1, -1));

        jPanel1.setBackground(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(934, 0, -1, 720));

        jPanel2.setBackground(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        dateText.setBackground(new java.awt.Color(102, 0, 0));
        dateText.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        dateText.setForeground(new java.awt.Color(102, 0, 0));
        dateText.setText("<DD-MM-YYYY>");
        add(dateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 97, -1, -1));

        timeText.setBackground(new java.awt.Color(102, 0, 0));
        timeText.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        timeText.setForeground(new java.awt.Color(102, 0, 0));
        timeText.setText("<TIME>");
        add(timeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 54, -1, -1));

        jlabel1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(102, 0, 0));
        jlabel1.setText("Cari");
        add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 106, -1, -1));

        jlabel2.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(102, 0, 0));
        jlabel2.setText("Pelanggan");
        add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 184, -1, -1));

        labelNamaStaff.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        labelNamaStaff.setForeground(new java.awt.Color(102, 0, 0));
        labelNamaStaff.setText("<Nama>");
        add(labelNamaStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 135, -1, -1));

        LabelNamaPelanggan.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        LabelNamaPelanggan.setForeground(new java.awt.Color(102, 0, 0));
        LabelNamaPelanggan.setText("Default");
        add(LabelNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 184, -1, -1));

        buttonPilihStaf.setBackground(new java.awt.Color(89, 38, 1));
        buttonPilihStaf.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        buttonPilihStaf.setForeground(java.awt.Color.white);
        buttonPilihStaf.setText("Pilih Staf");
        buttonPilihStaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPilihStafActionPerformed(evt);
            }
        });
        add(buttonPilihStaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 127, -1, 37));

        buttonPilihPelanggan.setBackground(new java.awt.Color(89, 38, 1));
        buttonPilihPelanggan.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        buttonPilihPelanggan.setForeground(java.awt.Color.white);
        buttonPilihPelanggan.setText("Pilih Pelanggan");
        buttonPilihPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPilihPelangganActionPerformed(evt);
            }
        });
        add(buttonPilihPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 176, -1, 37));

        tableProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Product", "Berat (gr)", "Karat", "Tipe", "Deskripsi", "Aksi"
            }
        ));
        tableProduk.setDefaultRenderer(Object.class, new CustomTableCellRenderer());
        jScrollPane1.setViewportView(tableProduk);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 139, 459, 130));

        tableTroli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Product", "Berat (gr)", "Karat", "Tipe", "Deskripsi", "Harga Jual", "Aksi"
            }
        ));
        tableTroli.setDefaultRenderer(Object.class, new CustomTableCellRenderer());
        jScrollPane2.setViewportView(tableTroli);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 360, 459, 135));

        TitleText1.setBackground(new java.awt.Color(102, 0, 0));
        TitleText1.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        TitleText1.setForeground(new java.awt.Color(102, 0, 0));
        TitleText1.setText("Troli");
        add(TitleText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 281, -1, -1));

        jlabel3.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(102, 0, 0));
        jlabel3.setText("Staff");
        add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 135, -1, -1));

        TitleText2.setBackground(new java.awt.Color(102, 0, 0));
        TitleText2.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        TitleText2.setForeground(new java.awt.Color(102, 0, 0));
        TitleText2.setText("Produk");
        add(TitleText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 54, -1, -1));

        jlabel4.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(102, 0, 0));
        jlabel4.setText("Cari");
        add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 327, -1, -1));

        fieldCariTroli.setForeground(java.awt.Color.gray);
        fieldCariTroli.setText("Ketik pencarian");
        fieldCariTroli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCariTroliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCariTroliFocusLost(evt);
            }
        });
        add(fieldCariTroli, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 324, 191, -1));

        jlabel5.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(102, 0, 0));
        jlabel5.setText("<HargaTotal>");
        add(jlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 513, -1, -1));

        jlabel6.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(102, 0, 0));
        jlabel6.setText("Total : ");
        add(jlabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 513, -1, -1));

        jlabel7.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel7.setForeground(new java.awt.Color(102, 0, 0));
        jlabel7.setText("Metode Bayar");
        add(jlabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 538, -1, -1));

        jRadioButton2.setText("Cash");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 557, -1, -1));

        jRadioButton3.setText("Credit");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 557, -1, -1));

        jRadioButton4.setText("Debit");
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 557, -1, -1));

        panelInfoProduk.setBackground(java.awt.Color.white);
        panelInfoProduk.setBorder(new BubbleBorderJPanel(Color.WHITE, 10, 20, 0));

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setText("Deskripsi:");

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("IDProduct");

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("IDProduct");

        jLabel9.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("IDProduct");

        jLabel10.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel10.setForeground(java.awt.Color.gray);
        jLabel10.setText("Weight:");

        jLabel11.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel11.setForeground(java.awt.Color.gray);
        jLabel11.setText("Karat:");

        jLabel12.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.black);
        jLabel12.setText("IDProduct");

        jLabel13.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel13.setForeground(java.awt.Color.gray);
        jLabel13.setText("Type:");

        jLabel14.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel14.setForeground(java.awt.Color.black);
        jLabel14.setText("IDProduct");

        jLabel15.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel15.setForeground(java.awt.Color.gray);
        jLabel15.setText("Kategori:");

        jLabel16.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.black);
        jLabel16.setText("IDProduct");

        jLabel17.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel17.setForeground(java.awt.Color.gray);
        jLabel17.setText("Supplier:");

        jLabel18.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel18.setForeground(java.awt.Color.black);
        jLabel18.setText("IDProduct");

        jLabel19.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel19.setForeground(java.awt.Color.gray);
        jLabel19.setText("Harga Beli:");

        jLabel20.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel20.setForeground(java.awt.Color.black);
        jLabel20.setText("IDProduct");

        javax.swing.GroupLayout panelInfoProdukLayout = new javax.swing.GroupLayout(panelInfoProduk);
        panelInfoProduk.setLayout(panelInfoProdukLayout);
        panelInfoProdukLayout.setHorizontalGroup(
            panelInfoProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        panelInfoProdukLayout.setVerticalGroup(
            panelInfoProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(1, 1, 1)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(1, 1, 1)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(1, 1, 1)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(1, 1, 1)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelInfoProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 281, 323, -1));

        jlabel8.setFont(new java.awt.Font("Myriad Pro", 0, 28)); // NOI18N
        jlabel8.setForeground(new java.awt.Color(102, 0, 0));
        jlabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Information_50px_4.png"))); // NOI18N
        jlabel8.setText("Info Produk");
        add(jlabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 219, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCariProdukFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCariProdukFocusGained
        if (fieldCariProduk.getText().equals("Ketik pencarian")) {
            fieldCariProduk.setText("");
            fieldCariProduk.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fieldCariProdukFocusGained

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void fieldCariProdukFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCariProdukFocusLost
        if (fieldCariProduk.getText().equals("")) {
            fieldCariProduk.setText("Ketik pencarian");
            fieldCariProduk.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_fieldCariProdukFocusLost

    private void buttonPilihStafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPilihStafActionPerformed
        JDialog pilihStafDialog = new JDialog();
        pilihStafDialog.setContentPane(new PilihStaf());
        pilihStafDialog.pack();
        pilihStafDialog.setLocationRelativeTo(this);
        pilihStafDialog.setVisible(true);
    }//GEN-LAST:event_buttonPilihStafActionPerformed

    private void buttonPilihPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPilihPelangganActionPerformed
        JDialog pilihPelangganDialog = new JDialog();
        pilihPelangganDialog.setContentPane(new PilihPelanggan());
        pilihPelangganDialog.pack();
        pilihPelangganDialog.setVisible(true);
    }//GEN-LAST:event_buttonPilihPelangganActionPerformed

    private void fieldCariTroliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCariTroliFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariTroliFocusGained

    private void fieldCariTroliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCariTroliFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariTroliFocusLost

    public static void main(String args[]) {
        JFrame a = new JFrame();
        a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Transaksi panel = new Transaksi();
        //a.setPreferredSize(dialog.getPreferredSize());
        a.setSize(panel.getPreferredSize());
        a.setContentPane(panel);
        a.setVisible(true);
        System.out.println("Width : " + a.getWidth());
        System.out.println("Height : " + a.getHeight());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNamaPelanggan;
    private javax.swing.JLabel TitleText;
    private javax.swing.JLabel TitleText1;
    private javax.swing.JLabel TitleText2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonPilihPelanggan;
    private javax.swing.JButton buttonPilihStaf;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel dateText;
    private javax.swing.JTextField fieldCariProduk;
    private javax.swing.JTextField fieldCariTroli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel labelNamaStaff;
    private javax.swing.JPanel panelInfoProduk;
    private javax.swing.JTable tableProduk;
    private javax.swing.JTable tableTroli;
    private javax.swing.JLabel timeText;
    // End of variables declaration//GEN-END:variables
}
