package panels;

/**
 *
 * @author Xenon
 */
import customComponents.*;
import java.awt.Color;
import javax.swing.JFrame;

public class Transaksi extends javax.swing.JPanel {

    /**
     * Creates new form Staff
     */
    public Transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        TitleText = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        fieldCariProduk = new javax.swing.JTextField();
        fieldCariProduk = new CorneredJTextField();
        jlabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dateText = new javax.swing.JLabel();
        timeText = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        labelNamaStaff = new javax.swing.JLabel();
        LabelNamaPelanggan = new javax.swing.JLabel();
        buttonPilihStaf = new javax.swing.JButton();
        buttonPilihPelanggan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        TitleText1 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        TitleText2 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        fieldCariProduk1 = new javax.swing.JTextField();
        fieldCariProduk1 = new CorneredJTextField();
        jlabel5 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        jlabel7 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 231, 192));
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(980, 720));

        TitleText.setBackground(new java.awt.Color(102, 0, 0));
        TitleText.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        TitleText.setForeground(new java.awt.Color(102, 0, 0));
        TitleText.setText("Transaksi");

        buttonTambah.setBackground(new java.awt.Color(89, 38, 1));
        buttonTambah.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        buttonTambah.setForeground(java.awt.Color.white);
        buttonTambah.setText("Tambah pelanggan");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        fieldCariProduk.setForeground(java.awt.Color.gray);
        fieldCariProduk.setText("Ketik pencarian");
        fieldCariProduk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCariProdukFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCariProdukFocusLost(evt);
            }
        });

        jlabel.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel.setForeground(new java.awt.Color(102, 0, 0));
        jlabel.setText("Tanggal Transaksi");

        jPanel1.setBackground(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dateText.setBackground(new java.awt.Color(102, 0, 0));
        dateText.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        dateText.setForeground(new java.awt.Color(102, 0, 0));
        dateText.setText("<DD-MM-YYYY>");

        timeText.setBackground(new java.awt.Color(102, 0, 0));
        timeText.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        timeText.setForeground(new java.awt.Color(102, 0, 0));
        timeText.setText("<TIME>");

        jlabel1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(102, 0, 0));
        jlabel1.setText("Cari");

        jlabel2.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(102, 0, 0));
        jlabel2.setText("Pelanggan");

        labelNamaStaff.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        labelNamaStaff.setForeground(new java.awt.Color(102, 0, 0));
        labelNamaStaff.setText("<Nama>");

        LabelNamaPelanggan.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        LabelNamaPelanggan.setForeground(new java.awt.Color(102, 0, 0));
        LabelNamaPelanggan.setText("Default");

        buttonPilihStaf.setBackground(new java.awt.Color(89, 38, 1));
        buttonPilihStaf.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        buttonPilihStaf.setForeground(java.awt.Color.white);
        buttonPilihStaf.setText("Pilih Staf");
        buttonPilihStaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPilihStafActionPerformed(evt);
            }
        });

        buttonPilihPelanggan.setBackground(new java.awt.Color(89, 38, 1));
        buttonPilihPelanggan.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        buttonPilihPelanggan.setForeground(java.awt.Color.white);
        buttonPilihPelanggan.setText("Pilih Pelanggan");
        buttonPilihPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPilihPelangganActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Product", "Berat (gr)", "Karat", "Tipe", "Deskripsi", "Aksi"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Product", "Berat (gr)", "Karat", "Tipe", "Deskripsi", "Aksi"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        TitleText1.setBackground(new java.awt.Color(102, 0, 0));
        TitleText1.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        TitleText1.setForeground(new java.awt.Color(102, 0, 0));
        TitleText1.setText("Troli");

        jlabel3.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(102, 0, 0));
        jlabel3.setText("Staff");

        TitleText2.setBackground(new java.awt.Color(102, 0, 0));
        TitleText2.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        TitleText2.setForeground(new java.awt.Color(102, 0, 0));
        TitleText2.setText("Produk");

        jlabel4.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(102, 0, 0));
        jlabel4.setText("Cari");

        fieldCariProduk1.setForeground(java.awt.Color.gray);
        fieldCariProduk1.setText("Ketik pencarian");
        fieldCariProduk1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCariProduk1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCariProduk1FocusLost(evt);
            }
        });

        jlabel5.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(102, 0, 0));
        jlabel5.setText("<HargaTotal>");

        jlabel6.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(102, 0, 0));
        jlabel6.setText("Total : ");

        jlabel7.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jlabel7.setForeground(new java.awt.Color(102, 0, 0));
        jlabel7.setText("Metode Bayar");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        jRadioButton4.setText("jRadioButton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlabel2)
                                        .addComponent(jlabel3))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelNamaStaff)
                                        .addComponent(LabelNamaPelanggan))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonPilihStaf)
                                        .addComponent(buttonPilihPelanggan))
                                    .addGap(82, 82, 82)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TitleText1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jlabel1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(fieldCariProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(122, 122, 122)
                                                    .addComponent(dateText))
                                                .addComponent(TitleText2)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(fieldCariProduk1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jlabel))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jRadioButton3)
                                .addGap(110, 110, 110)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlabel7)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jlabel5))
                                        .addComponent(buttonTambah, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TitleText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 620, Short.MAX_VALUE)
                                .addComponent(timeText)))
                        .addGap(27, 27, 27)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(TitleText)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timeText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TitleText2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlabel1)
                                    .addComponent(fieldCariProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TitleText1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel4)
                            .addComponent(fieldCariProduk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNamaStaff)
                            .addComponent(buttonPilihStaf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel2)
                            .addComponent(LabelNamaPelanggan)
                            .addComponent(buttonPilihPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel6)
                            .addComponent(jlabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addGap(71, 71, 71))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCariProdukFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCariProdukFocusGained
        if (fieldCariProduk.getText().equals("Ketik pencarian")) {
            fieldCariProduk.setText("");
            fieldCariProduk.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fieldCariProdukFocusGained

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void fieldCariProdukFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCariProdukFocusLost
        if (fieldCariProduk.getText().equals("")) {
            fieldCariProduk.setText("Ketik pencarian");
            fieldCariProduk.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_fieldCariProdukFocusLost

    private void buttonPilihStafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPilihStafActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPilihStafActionPerformed

    private void buttonPilihPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPilihPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPilihPelangganActionPerformed

    private void fieldCariProduk1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCariProduk1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariProduk1FocusGained

    private void fieldCariProduk1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCariProduk1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariProduk1FocusLost

    public static void main(String args[]) {
        JFrame a = new JFrame();
        a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Transaksi panel = new Transaksi();
        //a.setPreferredSize(dialog.getPreferredSize());
        a.setSize(panel.getPreferredSize());
        a.setContentPane(panel);
        a.setVisible(true);
        System.out.println("Width : " + a.getWidth());
        System.out.println("Height : " + a.getHeight());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNamaPelanggan;
    private javax.swing.JLabel TitleText;
    private javax.swing.JLabel TitleText1;
    private javax.swing.JLabel TitleText2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonPilihPelanggan;
    private javax.swing.JButton buttonPilihStaf;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel dateText;
    private javax.swing.JTextField fieldCariProduk;
    private javax.swing.JTextField fieldCariProduk1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel labelNamaStaff;
    private javax.swing.JLabel timeText;
    // End of variables declaration//GEN-END:variables
}
